### ISSUE TITLE
Migrate to .NET Core.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#106]
.NET Core and .NET Standard seems to be the future main .NET platform and as of today there are some improvements (i.e. performance) present in .NET Core that are not present or late in .NET Framework and more to come.

Therefore it seems reasonable for quite a new project to go with .NET Core and .NET Standard. Especially .NET Core 3 providing Windows Desktop Packs would allow to easily migrate all existing code from .NET Framework to .NET Core.

Things to do:
- [x] #172 Migrate Geisha.Common to .NET Core.
- [x] #173 Migrate Geisha.Common.TestUtils to .NET Core.
- [x] #174 Migrate Geisha.Common.UnitTests to .NET Core.
- [x] #175 Migrate Geisha.Common.IntegrationTests to .NET Core.
- [x] #176 Migrate Geisha.Engine to .NET Core.
- [x] #177 Migrate Geisha.Engine.UnitTests to .NET Core.
- [x] #178 Migrate Geisha.IntegrationTestsData to .NET Core.
- [x] #181 Migrate Geisha.Engine.Audio.CSCore.UnitTests to .NET Core.
- [x] #179 Migrate Geisha.Engine.IntegrationTests to .NET Core.
- [x] #184 Migrate Geisha.Engine.Host.Windows to .NET Core.
- [x] #183 Migrate Geisha.Engine.Rendering.DirectX to .NET Core.
- [x] #182 Migrate Geisha.Engine.Input.Windows to .NET Core.
- [x] #180 Migrate Geisha.Engine.Audio.CSCore to .NET Core.
- [x] #185 Migrate Geisha.TestGame to .NET Core.
- [x] #186 Migrate Geisha.Editor to .NET Core.
- [x] #187 Migrate Geisha.Editor.UnitTests to .NET Core.
- [x] #188 Migrate Geisha.Editor.IntegrationTests to .NET Core.
- [x] #189 Enable C# 8.0 Nullable Reference Types in all projects.
