### ISSUE TITLE
[Epic] Replace MEF with Autofac as a DI container.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#107]
**This issue was migrated.**

MEF is more limited as a DI container and produces hard to debug issues (if some export is missing then it often is very hard to find out which one it is). Autofac seems to give better control with simple API and much more friendly debugging experience. Therefore dependency injection architecture should be redesigned around Autofac.

However Autofac is not typical extendability solution while MEF is, therefore MEF is most likely to be used for managing extension points (to avoid custom assembly discovery and loading) while Autofac will manage composition of objects based on loaded assemblies.

Tasks:
- [x] Investigate Autofac as dependency injection container. [#108]
- [x] Design extendability architecture around MEF. [#109]
- [x] Use MEF extendability architecture in engine to run Engine.Core in host process composing dependancies with Autofac. [#110]
- [x] Use new extendability and composition architecture in Engine.Rendering. [#111]
- [x] Use new extendability and composition architecture in Engine.Input. [#112]
- [x] Use new extendability and composition architecture in Engine.Audio. [#113]
- [x] Use new extendability and composition architecture in Engine.Physics. [#114]
- [x] Use new extendability and composition architecture in Editor. [#115]
- [x] Align Engine.IntegrationTests with new extendability and composition architecture. [#116]
- [x] Verify that new extendability and composition architecture is documented (xml docs). [#117]
