### ISSUE TITLE
Implement camera view rectangle culling

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#356]
Rendering visual geometry outside of camera view rectangle is waste of computing time and should be avoided. Therefore culling of visual geometry outside of camera view rectangle should be implemented.

## Acceptance criteria:
- [x] Add additional rendering statistics (draw calls count). #487 
- [x] Prepare benchmarks dedicated for culling. #488 
- [x] Add additional rendering integration tests dedicated for culling. #490
- [x] Visual geometry outside of camera view rectangle is not issuing draw calls. #491 
- [x] Provide API on component level for computing bounding rectangles. #492
- [x] Rendering performance is increased.

## Definition of Done
- [x] Automated Tests - new and modified code is covered with automated tests
- [x] Documentation - new and modified APIs are documented
- [x] Performance - performance is verified to avoid regression
- [x] Compatibility - consider compatibility of APIs and functionality with previous version and provide upgrade path if possible
- [x] Demo Application - if new functionality should be showcased in Demo Application or existing functionality changed update Demo Application
- [x] Release Activities - if release process is affected update Release Activities issue template

**Comment by dawidkomorowski** [comment]
Prior to implementing this it would be beneficial to implement some kind of renderer instrumentation. Most important metric seems to be number of draw calls per frame. Additional metrics can be defined too.
