### ISSUE TITLE
Implement batch rendering of sprites

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#358]
Currently rendering of each sprite issues single draw call. If multiple sprites share the same texture rendering of all this sprites can be optimized to issue single draw call for all of them. It greatly decreases cost of CPU to GPU communication resulting in increased performance.

As order of rendering must be preserved the batching can be used as second level ordering to group sprites. Sprites that are in the same sorting layer and have the same order in layer can be grouped by texture to apply batch rendering.

- [x] Change Per Primitive AA to MSAA to enable Direct2D SpriteBatch #494
- [x] Add benchmarks dedicated for batch rendering of sprites #496
- [x] Add integration tests dedicated for batch rendering of sprites #501
- [ ] Implement batch rendering of sprites #503 

## Acceptance criteria:
* Rendering performance is increased.

## Definition of Done
- [x] Automated Tests - new and modified code is covered with automated tests
- [x] Documentation - new and modified APIs are documented
- [x] Performance - performance is verified to avoid regression
- [x] Compatibility - consider compatibility of APIs and functionality with previous version and provide upgrade path if possible
- [x] Demo Application - if new functionality should be showcased in Demo Application or existing functionality changed update Demo Application
- [x] Release Activities - if release process is affected update Release Activities issue template

**Comment by dawidkomorowski** [comment]
#494 changes anti aliasing mode from Direct2D Per Primitive to DXGI Multisampling. It turns out the latter is much slower on GitHub hosted runners so benchmarks show huge performance degradation. However, for the same change the same benchmarks were run on local physical hardware and results are quite opposite. For most benchmarks multisampling is slightly faster and for some it is much faster.

Therefore #494 was already merged to be a reference of benchmarks with MSAA and actual implementation of batch rendering of sprites will be in another PR.
