### ISSUE TITLE
[Epic] Extend the engine with functionality to load/store scenes from/to a file.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#65]
**This issue was migrated.**

Acceptance criteria:
- engine allows to load scene from a file
- engine allows to store scene to a file
- it is possible to define initial scene (scene file to be loaded at engine start up)

Tasks:
- [x] Save to a file and load from a file a Scene itself. [#68]
- [x] Save/load entities structure in Scene. [#69]
- [x] Save/load entity state (excluding components). [#70]
- [x] Save/load components of entity. [#71]
- [x] Introduce an AssetStore. [#72]
- [x] Support of save/load for SpriteRenderer. [#73]
- [x] Support InputMapping asset load. [#74]
- [x] Support of save/load for InputComponent. [#75]
- [x] Support of save/load for Camera. [#76]
- [x] Support of save/load for collider components. [#77]
- [x] Support of save/load for behavior components. [#78]
- [x] Support of save/load for TextRenderer. [#79]
- [x] Support Sound asset load. [#80]
- [x] Support of save/load for AudioSource. [#81]
- [x] Add configuration property to set startup scene. [#82]
- [x] Consider implementing integration tests of SceneLoader. [#85]
