### ISSUE TITLE
[Epic] Enable engine to switch between scenes.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#66]
**This issue was migrated.**

- engine provides API to change currently running scene (possibly load scene from file on demand)
- consider loading next scene in background while running current one
- consider adding concept of Construction Scripts that allow to run custom post processing after loading scene (creating some entities dynamically, randomizing things i.e. level layout, loading saved game, etc.)

Tasks:
- [x] Implement ConstructionScript concept. [#130]
- [x] Implement automatic assets discovery and registration. [#127]
- [x] Remove IStartUpTask. [#134]
- [x] Extend ISceneManager with API to change current scene. [#133]
