### ISSUE TITLE
[Epic] Very poor rendering performance.

### ISSUE THREAD

**Issue by dawidkomorowski** [dawidkomorowski/geisha#90]
**This issue was migrated.**

Game engine struggles to run at acceptable framerate even at very small number of entities present in scene. It is mainly due to very poor performance of rendering backend as with empty scene it runs rather slow and with several tens of sprites on screen it is clearly lagging and not able to provide fluent framerate.

Tasks:
- [x] Investigate SharpDX applicability as a DirectX API for new DirectX rendering backend. [#91]
- [x] Verify SharpDX performance. [#92]
- [x] Implement DirectX version of IRenderer2D - initialization of DirectX and Clear. [#95]
- [x] Implement DirectX version of IRenderer2D - texture creation. [#96]
- [x] Implement DirectX version of IRenderer2D - sprite rendering. [#97]
- [x] Implement DirectX version of IRenderer2D - text rendering. [#93]
- [x] Implement engine host (launcher) creating window with DirectX device. [#94]
- [x] Remove Geisha.SharpDXTestApp project from solution. [#100]
- [x] Add missing documentation in IRenderer2D and related code. [ #102]
